routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\userController as ObagzAuth;
use App\Models\AdminverifyEmailAddress;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\obagz_admin\ForgotPasswordController as AdminForgotPassword;
use App\Http\Controllers\obagz_admin\ResetPasswordController as AdminResetPassword;

use App\Http\Controllers\obagz_user\ForgotPasswordController as UserForgotPassword;
use App\Http\Controllers\obagz_user\ResetPasswordController as UserResetPassword;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('obagz_home');
})->name('obagz');

Auth::routes();
//auth-routes
    //Admin
Route::prefix('admin')->name('admin.')->group(function(){
    Route::middleware(['guest:admin','preventBackHistory'])->group(function(){   
        Route::post('/register', [ObagzAuth::class, 'createObagzAdmin'])->name('register');
        Route::post('/login', [ObagzAuth::class, 'loginObagzAdmin'])->name('login');
   
        Route::view('/login', 'obagz-auth.login', ['url' => 'admin'])->name('login');
        Route::view('/register', 'obagz-auth.register', ['url' => 'admin'])->name('register');
        Route::get('/verify',  [ObagzAuth::class, 'verifyAdmin'])->name('verify');
    });
    Route::middleware(['checkIfAdminVerified','auth:admin','preventBackHistory'])->group(function(){
        Route::view('/home', 'admin.admin-panel')->name('home');
        
    });
    Route::middleware(['dontShowIfVerified'])->group(function(){
        Route::view('/reverify',  'obagz-auth.verify', ['url' => 'admin'])->name('reVerify');
        Route::get('/reVerifyEmail',  [ObagzAuth::class, 'reVerifyAdmin'])->name('reVerifyEmail');
        
    });

    Route::post('/password/email', [AdminForgotPassword::class, 'sendResetLinkEmail'])->name('password.email');
    Route::get('/password/reset', [AdminForgotPassword::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('/password/reset', [AdminResetPassword::class, 'reset'])->name('password.update');
    Route::get('/password/reset/{token}', [AdminResetPassword::class, 'showResetForm'])->name('password.reset');
});

Route::prefix('user')->name('user.')->group(function(){
    Route::middleware(['guest:web','preventBackHistory'])->group(function(){
        Route::post('/register', [ObagzAuth::class, 'createObagzUsers'])->name('register');
        Route::post('/login', [ObagzAuth::class, 'loginObagzUsers'])->name('login');
        Route::get('/verify',  [ObagzAuth::class, 'verifyUser'])->name('verify');

        Route::view('/login', 'obagz-auth.login')->name('login');
        Route::view('/register', 'obagz-auth.register')->name('register');

    });

    Route::middleware(['dontShowIfVerified'])->group(function(){
        Route::view('/reverify',  'obagz-auth.verify')->name('reVerify');
        Route::get('/reVerifyEmail',  [ObagzAuth::class, 'reVerifyUser'])->name('reVerifyEmail');
        
    });

    Route::post('/password/email', [UserForgotPassword::class, 'sendResetLinkEmail'])->name('password.email');
    Route::get('/password/reset', [UserForgotPassword::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('/password/reset', [UserResetPassword::class, 'reset'])->name('password.update');
    Route::get('/password/reset/{token}', [UserResetPassword::class, 'showResetForm'])->name('password.reset');
});



// Auth::routes(['verify'=>true]);
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/test', function(){
   return view('obagz-auth.loginUser');
});
Route::get('/test2', function(){
    return view('obagz-auth.registerUser');
 });

resources/views/obagz-auth/login.blade.php
@extends('layouts.without-header')
@section('content')
    <div class="l-container" id="container">
        <div class="form-container sign-in-container">
            @isset($url)
                <form  method="POST" action="{{ route('admin.login') }}">
                @else
                    <form method="POST" action="{{ route('login') }}">
                    @endisset
                    @csrf
                    <h1>Sign In</h1>
                    <div class="social-container">
                        <a href="#" class="social"><i class="bi bi-facebook"></i></a>
                        <a href="#" class="social"><i class="bi bi-google"></i></i></a>
                        <a href="#" class="social"><i class="bi bi-instagram"></i></a>
                    </div>
                    <span>or use your account</span>
                    @if (Session::get('fail'))
                        <span class="error-message">
                            {{ Session::get('fail') }}
                        </span>
                    @endif
                    @if (Session::get('success'))
                        <span class="success-message">
                            {{ Session::get('success') }}
                        </span>
                    @endif
                    <input  type="text" id="login-email"
                        placeholder="Enter E-mail" @error('email') is-invalid @enderror" name="email"
                        value="{{ old('email') }}" autocomplete="email" autofocus>
                    @error('email')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                    <input  type="password" id="login-password"
                        placeholder="Enter Password" @error('password') is-invalid @enderror" name="password"
                        value="{{ old('password') }}" autocomplete="password" autofocus>
                    @error('password')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                    @if (Route::has('password.request'))
                        <a  href="
                    @isset($url)
                        {{ route('admin.password.request') }}
                    @else
                        {{ route('user.password.request') }}
                    @endisset
                    ">
                            {{ __('Forgot Your Password?') }}
                        </a>
                    @endif
                    <button type="submit">Sign In</button>
                </form>
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-right">
                    <h1>Hello, Friend!</h1>
                    <p>Enter your personal details and start your journey with us</p>
                    <a href="{{route('user.register')}}"><button class="ghost" id="signUp">Sign Up</button></a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/obagz-auth/register.blade.php
@extends('layouts.without-header')
@section('content')
    <div class="l-container right-panel-active" id="container">
        <div class="form-container sign-up-container">
            @isset($url)
                <form method="POST" action="{{ route('admin.register') }}">
                @else
                    <form method="POST" action="{{ route('user.register') }}">
                    @endisset
                    @csrf
                    <h1>Sign Up</h1>
                    <div class="social-container">
                        <a href="#" class="social"><i class="bi bi-facebook"></i></a>
                        <a href="#" class="social"><i class="bi bi-google"></i></i></a>
                        <a href="#" class="social"><i class="bi bi-instagram"></i></a>
                    </div>
                    <span>or use your email for registration</span>
                    @if (Session::get('success'))
                        <span class="success-message">
                            {{ Session::get('success') }}
                        </span>
                    @endif
                    @if (Session::get('fail'))
                        <span class="error-message">
                            {{ Session::get('fail') }}
                        </span>
                    @endif
                    <input type="text" id="name" placeholder="Full Name" @error('name') is-invalid @enderror"
                        name="name" value="{{ old('name') }}" autocomplete="name" autofocus>
                    @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                    <input type="text" id="email" placeholder="Enter E-mail" @error('email') is-invalid @enderror"
                        name="email" value="{{ old('email') }}" autocomplete="email" autofocus>
                    @error('email')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror


                    <input type="password" id="password" placeholder="Enter Password" @error('password') is-invalid
                        @enderror" name="password" value="{{ old('password') }}" autocomplete="password" autofocus>
                    @error('password')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                    <input id="password-confirm" type="password" name="password_confirmation"
                         autocomplete="new-password" placeholder="retype password">

                    <button type="submit">Sign Up</button>
                </form>
        </div>

        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>Welcome Back!</h1>
                    <p>Please login with your personal info</p>
                    <a href="{{route('user.login')}}"><button class="ghost" id="signUp">Sign In</button></a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/obagz-auth/verify.blade.php
@extends('layouts.without-header')
@section('content')
  
        @if (Session::get('success'))
            <div>
                <span class="success-message" style="font-size: 1rem">
                    {{ Session::get('success') }}
                </span>
            </div>
        @endif
        
        <h3>Didn't get verification link?</h3>
        @isset($url)
        <a href="{{route('admin.reVerifyEmail')}}"><button>resend email verification link</button></a>
        @else
        <a href="{{route('user.reVerifyEmail')}}"><button>resend email verification link</button></a>
        @endisset

  
@endsection